name: 'Setup Go'
description: 'Sets up a specific Go version'

# Define the inputs this action will accept
inputs:
  go-version:
    description: 'Go version to install'
    required: true

runs:
  using: 'composite' # Mark this as a composite action
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
