version: "2"

run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - errcheck
    - govet
    - ineffassign
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (*github.com/gin-gonic/gin.Context).Error
