default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  # Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        name: conventional-pre-commit
        description: Conventional commit message validator
        args: [feat, fix, docs, style, refactor, test, chore]

  # Go tools
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt
        stages: [pre-commit]
        name: go-fmt
        description: Format Go files with gofmt
        entry: gofmt -w -s
        types: [go]
        language: system
        args: [.]
        require_serial: true

      - id: go-imports
        stages: [pre-commit]
        name: go-imports
        description: Update Go import lines
        entry: goimports -w
        types: [go]
        language: system
        args: [.]
        require_serial: true

      - id: go-vet
        stages: [pre-commit]
        name: go-vet
        description: Report likely mistakes in Go code
        entry: go vet
        language: system
        pass_filenames: false
        args: [./...]
        require_serial: true

      - id: go-mod-tidy
        stages: [pre-commit]
        name: go-mod-tidy
        description: Tidy Go module dependencies

  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
        name: check-yaml
        description: Check YAML files for syntax errors

      - id: end-of-file-fixer
        stages: [pre-commit]
        name: end-of-file-fixer
        description: Fix end of file issues

      - id: trailing-whitespace
        stages: [pre-commit]
        name: trailing-whitespace
        description: Remove trailing whitespace

      - id: check-added-large-files
        stages: [pre-commit]
        name: check-added-large-files
        description: Check added large files
        args: [--maxkb=1024]
