# Path to coverage profile file (output of `go test -coverprofile` command)
profile: coverage.out

# Holds coverage thresholds percentages, values should be in range [0-100]
threshold:
  # Minimum coverage percentage required for individual files
  file: 70
  # Minimum coverage percentage required for each package
  package: 75
  # Minimum overall project coverage percentage required
  total: 80

# Holds regexp rules which will exclude matched files or packages from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - \.pb\.go$              # excludes all protobuf generated files
    - ^cmd/                  # exclude cmd directory
    - ^internal/config/      # exclude config directory
    - ^internal/domain/      # exclude domain directory
    - ^internal/infrastructure/  # exclude infrastructure directory
    - ^internal/presentation/    # exclude presentation directory
    - ^internal/utils/       # exclude utils directory
    - /mocks/                # exclude mock files
    - _test\.go$             # exclude test files themselves

# Override rules for specific paths (optional)
# override:
#   - path: ^internal/domain
#     threshold: 90

# Badge configuration (optional)
badge:
  file-name: coverage.svg
