db.products.insertMany([
    {"name": "Laptop Pro", "description": "High-performance laptop for professionals", "price": 1200.00, "stock": 50, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Smartphone X", "description": "Latest model with advanced features", "price": 800.00, "stock": 150, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Wireless Headphones", "description": "Noise-cancelling over-ear headphones", "price": 250.00, "stock": 300, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Smartwatch 2", "description": "Fitness tracking and mobile notifications", "price": 180.00, "stock": 200, "created_at": new Date(), "updated_at": new Date() },
    {"name": "4K Monitor", "description": "27-inch monitor with ultra-high definition", "price": 450.00, "stock": 80, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Mechanical Keyboard", "description": "RGB backlit keyboard for gaming", "price": 120.00, "stock": 120, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Webcam HD", "description": "1080p webcam for video conferencing", "price": 60.00, "stock": 250, "created_at": new Date(), "updated_at": new Date() },
    {"name": "USB-C Hub", "description": "Multi-port adapter for laptops", "price": 40.00, "stock": 400, "created_at": new Date(), "updated_at": new Date() },
    {"name": "External SSD 1TB", "description": "High-speed portable storage", "price": 150.00, "stock": 100, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Gaming Mouse", "description": "Ergonomic mouse with customizable buttons", "price": 80.00, "stock": 180, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Standing Desk", "description": "Adjustable height desk for home office", "price": 350.00, "stock": 60, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Ergonomic Chair", "description": "Office chair with lumbar support", "price": 280.00, "stock": 90, "created_at": new Date(), "updated_at": new Date() },
    {"name": "LED Desk Lamp", "description": "Modern lamp with adjustable brightness", "price": 35.00, "stock": 300, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Portable Charger", "description": "20000mAh power bank for mobile devices", "price": 50.00, "stock": 220, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Bluetooth Speaker", "description": "Waterproof speaker for outdoor use", "price": 70.00, "stock": 170, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Graphics Tablet", "description": "For digital drawing and photo editing", "price": 100.00, "stock": 110, "created_at": new Date(), "updated_at": new Date() },
    {"name": "VR Headset", "description": "Immersive virtual reality experience", "price": 400.00, "stock": 70, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Drone with Camera", "description": "4K video recording drone", "price": 600.00, "stock": 40, "created_at": new Date(), "updated_at": new Date() },
    {"name": "E-reader", "description": "Backlit e-reader with long battery life", "price": 130.00, "stock": 190, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Fitness Tracker", "description": "Monitors heart rate and daily activity", "price": 60.00, "stock": 280, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Electric Toothbrush", "description": "With multiple cleaning modes", "price": 90.00, "stock": 140, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Coffee Maker", "description": "12-cup programmable coffee machine", "price": 80.00, "stock": 160, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Blender", "description": "High-speed blender for smoothies", "price": 110.00, "stock": 130, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Air Fryer", "description": "For healthy, oil-free cooking", "price": 100.00, "stock": 200, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Robot Vacuum", "description": "Automated cleaning for your home", "price": 300.00, "stock": 80, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Security Camera", "description": "Indoor/outdoor security camera", "price": 120.00, "stock": 150, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Smart Thermostat", "description": "Energy-saving home thermostat", "price": 150.00, "stock": 100, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Wi-Fi Router", "description": "High-speed dual-band router", "price": 100.00, "stock": 180, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Projector", "description": "1080p home theater projector", "price": 500.00, "stock": 50, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Soundbar", "description": "For enhanced TV audio", "price": 200.00, "stock": 90, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Action Camera", "description": "Waterproof camera for sports", "price": 250.00, "stock": 120, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Digital Photo Frame", "description": "Displays a slideshow of your photos", "price": 70.00, "stock": 200, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Electric Kettle", "description": "Fast-boiling water kettle", "price": 40.00, "stock": 250, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Microwave Oven", "description": "Compact microwave for small spaces", "price": 90.00, "stock": 110, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Toaster", "description": "2-slice toaster with wide slots", "price": 30.00, "stock": 300, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Hair Dryer", "description": "Ionic hair dryer for fast drying", "price": 50.00, "stock": 170, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Electric Shaver", "description": "For a close and comfortable shave", "price": 80.00, "stock": 140, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Yoga Mat", "description": "Non-slip mat for yoga and exercise", "price": 25.00, "stock": 400, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Dumbbell Set", "description": "Adjustable dumbbell set for home gym", "price": 150.00, "stock": 80, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Resistance Bands", "description": "Set of 5 bands for strength training", "price": 20.00, "stock": 500, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Water Bottle", "description": "Insulated stainless steel water bottle", "price": 20.00, "stock": 600, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Backpack", "description": "Durable backpack for travel and work", "price": 60.00, "stock": 250, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Sunglasses", "description": "UV protection sunglasses", "price": 40.00, "stock": 350, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Wristwatch", "description": "Classic analog wristwatch", "price": 120.00, "stock": 180, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Wallet", "description": "Leather wallet with RFID blocking", "price": 30.00, "stock": 400, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Desk Organizer", "description": "Keeps your desk tidy", "price": 20.00, "stock": 300, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Notebook and Pen Set", "description": "Premium notebook and pen", "price": 25.00, "stock": 450, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Wall Art", "description": "Abstract canvas print for home decor", "price": 80.00, "stock": 120, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Scented Candle", "description": "Soy wax candle with lavender scent", "price": 15.00, "stock": 500, "created_at": new Date(), "updated_at": new Date() },
    {"name": "Board Game", "description": "Strategy board game for game night", "price": 40.00, "stock": 200, "created_at": new Date(), "updated_at": new Date() }
]);