// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mail

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMailSenderMock creates a new instance of MailSenderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailSenderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailSenderMock {
	mock := &MailSenderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MailSenderMock is an autogenerated mock type for the MailSender type
type MailSenderMock struct {
	mock.Mock
}

type MailSenderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MailSenderMock) EXPECT() *MailSenderMock_Expecter {
	return &MailSenderMock_Expecter{mock: &_m.Mock}
}

// SendEmail provides a mock function for the type MailSenderMock
func (_mock *MailSenderMock) SendEmail(ctx context.Context, to string, subject string, file string, data any) error {
	ret := _mock.Called(ctx, to, subject, file, data)

	if len(ret) == 0 {
		panic("no return value specified for SendEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, any) error); ok {
		r0 = returnFunc(ctx, to, subject, file, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MailSenderMock_SendEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmail'
type MailSenderMock_SendEmail_Call struct {
	*mock.Call
}

// SendEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - subject string
//   - file string
//   - data any
func (_e *MailSenderMock_Expecter) SendEmail(ctx interface{}, to interface{}, subject interface{}, file interface{}, data interface{}) *MailSenderMock_SendEmail_Call {
	return &MailSenderMock_SendEmail_Call{Call: _e.mock.On("SendEmail", ctx, to, subject, file, data)}
}

func (_c *MailSenderMock_SendEmail_Call) Run(run func(ctx context.Context, to string, subject string, file string, data any)) *MailSenderMock_SendEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MailSenderMock_SendEmail_Call) Return(err error) *MailSenderMock_SendEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MailSenderMock_SendEmail_Call) RunAndReturn(run func(ctx context.Context, to string, subject string, file string, data any) error) *MailSenderMock_SendEmail_Call {
	_c.Call.Return(run)
	return _c
}
