// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package customer

import (
	"context"

	"github.com/goodone-dev/go-boilerplate/internal/domain/customer"
	"github.com/goodone-dev/go-boilerplate/internal/infrastructure/database"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewCustomerRepositoryMock creates a new instance of CustomerRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCustomerRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CustomerRepositoryMock {
	mock := &CustomerRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CustomerRepositoryMock is an autogenerated mock type for the CustomerRepository type
type CustomerRepositoryMock struct {
	mock.Mock
}

type CustomerRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CustomerRepositoryMock) EXPECT() *CustomerRepositoryMock_Expecter {
	return &CustomerRepositoryMock_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) Begin(ctx context.Context) (*gorm.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type CustomerRepositoryMock_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CustomerRepositoryMock_Expecter) Begin(ctx interface{}) *CustomerRepositoryMock_Begin_Call {
	return &CustomerRepositoryMock_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *CustomerRepositoryMock_Begin_Call) Run(run func(ctx context.Context)) *CustomerRepositoryMock_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_Begin_Call) Return(dB *gorm.DB, err error) *CustomerRepositoryMock_Begin_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *CustomerRepositoryMock_Begin_Call) RunAndReturn(run func(ctx context.Context) (*gorm.DB, error)) *CustomerRepositoryMock_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) Commit(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// CustomerRepositoryMock_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type CustomerRepositoryMock_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) Commit(trx interface{}) *CustomerRepositoryMock_Commit_Call {
	return &CustomerRepositoryMock_Commit_Call{Call: _e.mock.On("Commit", trx)}
}

func (_c *CustomerRepositoryMock_Commit_Call) Run(run func(trx *gorm.DB)) *CustomerRepositoryMock_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_Commit_Call) Return(dB *gorm.DB) *CustomerRepositoryMock_Commit_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *CustomerRepositoryMock_Commit_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *CustomerRepositoryMock_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) DeleteById(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerRepositoryMock_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type CustomerRepositoryMock_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) DeleteById(ctx interface{}, ID interface{}, trx interface{}) *CustomerRepositoryMock_DeleteById_Call {
	return &CustomerRepositoryMock_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, ID, trx)}
}

func (_c *CustomerRepositoryMock_DeleteById_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *CustomerRepositoryMock_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_DeleteById_Call) Return(err error) *CustomerRepositoryMock_DeleteById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerRepositoryMock_DeleteById_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error) *CustomerRepositoryMock_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIds provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) DeleteByIds(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerRepositoryMock_DeleteByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIds'
type CustomerRepositoryMock_DeleteByIds_Call struct {
	*mock.Call
}

// DeleteByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) DeleteByIds(ctx interface{}, IDs interface{}, trx interface{}) *CustomerRepositoryMock_DeleteByIds_Call {
	return &CustomerRepositoryMock_DeleteByIds_Call{Call: _e.mock.On("DeleteByIds", ctx, IDs, trx)}
}

func (_c *CustomerRepositoryMock_DeleteByIds_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB)) *CustomerRepositoryMock_DeleteByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_DeleteByIds_Call) Return(err error) *CustomerRepositoryMock_DeleteByIds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerRepositoryMock_DeleteByIds_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error) *CustomerRepositoryMock_DeleteByIds_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) DeleteMany(ctx context.Context, filter map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, filter, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, filter, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerRepositoryMock_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type CustomerRepositoryMock_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) DeleteMany(ctx interface{}, filter interface{}, trx interface{}) *CustomerRepositoryMock_DeleteMany_Call {
	return &CustomerRepositoryMock_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, filter, trx)}
}

func (_c *CustomerRepositoryMock_DeleteMany_Call) Run(run func(ctx context.Context, filter map[string]any, trx *gorm.DB)) *CustomerRepositoryMock_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_DeleteMany_Call) Return(err error) *CustomerRepositoryMock_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerRepositoryMock_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, trx *gorm.DB) error) *CustomerRepositoryMock_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) FindAll(ctx context.Context, filter map[string]any) ([]customer.Customer, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) ([]customer.Customer, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) []customer.Customer); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customer.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type CustomerRepositoryMock_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
func (_e *CustomerRepositoryMock_Expecter) FindAll(ctx interface{}, filter interface{}) *CustomerRepositoryMock_FindAll_Call {
	return &CustomerRepositoryMock_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *CustomerRepositoryMock_FindAll_Call) Run(run func(ctx context.Context, filter map[string]any)) *CustomerRepositoryMock_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_FindAll_Call) Return(customers []customer.Customer, err error) *CustomerRepositoryMock_FindAll_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *CustomerRepositoryMock_FindAll_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any) ([]customer.Customer, error)) *CustomerRepositoryMock_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCursor provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) FindByCursor(ctx context.Context, filter map[string]any, sort []string, size int, next *uuid.UUID) (database.Pagination[customer.Customer], error) {
	ret := _mock.Called(ctx, filter, sort, size, next)

	if len(ret) == 0 {
		panic("no return value specified for FindByCursor")
	}

	var r0 database.Pagination[customer.Customer]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, *uuid.UUID) (database.Pagination[customer.Customer], error)); ok {
		return returnFunc(ctx, filter, sort, size, next)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, *uuid.UUID) database.Pagination[customer.Customer]); ok {
		r0 = returnFunc(ctx, filter, sort, size, next)
	} else {
		r0 = ret.Get(0).(database.Pagination[customer.Customer])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, []string, int, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, filter, sort, size, next)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_FindByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCursor'
type CustomerRepositoryMock_FindByCursor_Call struct {
	*mock.Call
}

// FindByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - sort []string
//   - size int
//   - next *uuid.UUID
func (_e *CustomerRepositoryMock_Expecter) FindByCursor(ctx interface{}, filter interface{}, sort interface{}, size interface{}, next interface{}) *CustomerRepositoryMock_FindByCursor_Call {
	return &CustomerRepositoryMock_FindByCursor_Call{Call: _e.mock.On("FindByCursor", ctx, filter, sort, size, next)}
}

func (_c *CustomerRepositoryMock_FindByCursor_Call) Run(run func(ctx context.Context, filter map[string]any, sort []string, size int, next *uuid.UUID)) *CustomerRepositoryMock_FindByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 *uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_FindByCursor_Call) Return(res database.Pagination[customer.Customer], err error) *CustomerRepositoryMock_FindByCursor_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *CustomerRepositoryMock_FindByCursor_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, sort []string, size int, next *uuid.UUID) (database.Pagination[customer.Customer], error)) *CustomerRepositoryMock_FindByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) FindById(ctx context.Context, ID uuid.UUID) (*customer.Customer, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*customer.Customer, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *customer.Customer); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type CustomerRepositoryMock_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *CustomerRepositoryMock_Expecter) FindById(ctx interface{}, ID interface{}) *CustomerRepositoryMock_FindById_Call {
	return &CustomerRepositoryMock_FindById_Call{Call: _e.mock.On("FindById", ctx, ID)}
}

func (_c *CustomerRepositoryMock_FindById_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *CustomerRepositoryMock_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_FindById_Call) Return(customer1 *customer.Customer, err error) *CustomerRepositoryMock_FindById_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *CustomerRepositoryMock_FindById_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*customer.Customer, error)) *CustomerRepositoryMock_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdAndLock provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) FindByIdAndLock(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (*customer.Customer, error) {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdAndLock")
	}

	var r0 *customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) (*customer.Customer, error)); ok {
		return returnFunc(ctx, ID, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) *customer.Customer); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*customer.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_FindByIdAndLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdAndLock'
type CustomerRepositoryMock_FindByIdAndLock_Call struct {
	*mock.Call
}

// FindByIdAndLock is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) FindByIdAndLock(ctx interface{}, ID interface{}, trx interface{}) *CustomerRepositoryMock_FindByIdAndLock_Call {
	return &CustomerRepositoryMock_FindByIdAndLock_Call{Call: _e.mock.On("FindByIdAndLock", ctx, ID, trx)}
}

func (_c *CustomerRepositoryMock_FindByIdAndLock_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *CustomerRepositoryMock_FindByIdAndLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_FindByIdAndLock_Call) Return(customer1 *customer.Customer, err error) *CustomerRepositoryMock_FindByIdAndLock_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *CustomerRepositoryMock_FindByIdAndLock_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (*customer.Customer, error)) *CustomerRepositoryMock_FindByIdAndLock_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIds provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) FindByIds(ctx context.Context, IDs []uuid.UUID) ([]customer.Customer, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 []customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]customer.Customer, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []customer.Customer); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customer.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_FindByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIds'
type CustomerRepositoryMock_FindByIds_Call struct {
	*mock.Call
}

// FindByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *CustomerRepositoryMock_Expecter) FindByIds(ctx interface{}, IDs interface{}) *CustomerRepositoryMock_FindByIds_Call {
	return &CustomerRepositoryMock_FindByIds_Call{Call: _e.mock.On("FindByIds", ctx, IDs)}
}

func (_c *CustomerRepositoryMock_FindByIds_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *CustomerRepositoryMock_FindByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_FindByIds_Call) Return(customers []customer.Customer, err error) *CustomerRepositoryMock_FindByIds_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *CustomerRepositoryMock_FindByIds_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) ([]customer.Customer, error)) *CustomerRepositoryMock_FindByIds_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOffset provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) FindByOffset(ctx context.Context, filter map[string]any, sort []string, size int, page int) (database.Pagination[customer.Customer], error) {
	ret := _mock.Called(ctx, filter, sort, size, page)

	if len(ret) == 0 {
		panic("no return value specified for FindByOffset")
	}

	var r0 database.Pagination[customer.Customer]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, int) (database.Pagination[customer.Customer], error)); ok {
		return returnFunc(ctx, filter, sort, size, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, int) database.Pagination[customer.Customer]); ok {
		r0 = returnFunc(ctx, filter, sort, size, page)
	} else {
		r0 = ret.Get(0).(database.Pagination[customer.Customer])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, []string, int, int) error); ok {
		r1 = returnFunc(ctx, filter, sort, size, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_FindByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOffset'
type CustomerRepositoryMock_FindByOffset_Call struct {
	*mock.Call
}

// FindByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - sort []string
//   - size int
//   - page int
func (_e *CustomerRepositoryMock_Expecter) FindByOffset(ctx interface{}, filter interface{}, sort interface{}, size interface{}, page interface{}) *CustomerRepositoryMock_FindByOffset_Call {
	return &CustomerRepositoryMock_FindByOffset_Call{Call: _e.mock.On("FindByOffset", ctx, filter, sort, size, page)}
}

func (_c *CustomerRepositoryMock_FindByOffset_Call) Run(run func(ctx context.Context, filter map[string]any, sort []string, size int, page int)) *CustomerRepositoryMock_FindByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_FindByOffset_Call) Return(res database.Pagination[customer.Customer], err error) *CustomerRepositoryMock_FindByOffset_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *CustomerRepositoryMock_FindByOffset_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, sort []string, size int, page int) (database.Pagination[customer.Customer], error)) *CustomerRepositoryMock_FindByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) Insert(ctx context.Context, model customer.Customer, trx *gorm.DB) (customer.Customer, error) {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, customer.Customer, *gorm.DB) (customer.Customer, error)); ok {
		return returnFunc(ctx, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, customer.Customer, *gorm.DB) customer.Customer); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Get(0).(customer.Customer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, customer.Customer, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type CustomerRepositoryMock_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model customer.Customer
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) Insert(ctx interface{}, model interface{}, trx interface{}) *CustomerRepositoryMock_Insert_Call {
	return &CustomerRepositoryMock_Insert_Call{Call: _e.mock.On("Insert", ctx, model, trx)}
}

func (_c *CustomerRepositoryMock_Insert_Call) Run(run func(ctx context.Context, model customer.Customer, trx *gorm.DB)) *CustomerRepositoryMock_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 customer.Customer
		if args[1] != nil {
			arg1 = args[1].(customer.Customer)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_Insert_Call) Return(customer1 customer.Customer, err error) *CustomerRepositoryMock_Insert_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *CustomerRepositoryMock_Insert_Call) RunAndReturn(run func(ctx context.Context, model customer.Customer, trx *gorm.DB) (customer.Customer, error)) *CustomerRepositoryMock_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) InsertMany(ctx context.Context, models []customer.Customer, trx *gorm.DB) ([]customer.Customer, error) {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []customer.Customer, *gorm.DB) ([]customer.Customer, error)); ok {
		return returnFunc(ctx, models, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []customer.Customer, *gorm.DB) []customer.Customer); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]customer.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []customer.Customer, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, models, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type CustomerRepositoryMock_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []customer.Customer
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) InsertMany(ctx interface{}, models interface{}, trx interface{}) *CustomerRepositoryMock_InsertMany_Call {
	return &CustomerRepositoryMock_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models, trx)}
}

func (_c *CustomerRepositoryMock_InsertMany_Call) Run(run func(ctx context.Context, models []customer.Customer, trx *gorm.DB)) *CustomerRepositoryMock_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []customer.Customer
		if args[1] != nil {
			arg1 = args[1].([]customer.Customer)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_InsertMany_Call) Return(customers []customer.Customer, err error) *CustomerRepositoryMock_InsertMany_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *CustomerRepositoryMock_InsertMany_Call) RunAndReturn(run func(ctx context.Context, models []customer.Customer, trx *gorm.DB) ([]customer.Customer, error)) *CustomerRepositoryMock_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// MasterDB provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) MasterDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MasterDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// CustomerRepositoryMock_MasterDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MasterDB'
type CustomerRepositoryMock_MasterDB_Call struct {
	*mock.Call
}

// MasterDB is a helper method to define mock.On call
func (_e *CustomerRepositoryMock_Expecter) MasterDB() *CustomerRepositoryMock_MasterDB_Call {
	return &CustomerRepositoryMock_MasterDB_Call{Call: _e.mock.On("MasterDB")}
}

func (_c *CustomerRepositoryMock_MasterDB_Call) Run(run func()) *CustomerRepositoryMock_MasterDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomerRepositoryMock_MasterDB_Call) Return(dB *gorm.DB) *CustomerRepositoryMock_MasterDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *CustomerRepositoryMock_MasterDB_Call) RunAndReturn(run func() *gorm.DB) *CustomerRepositoryMock_MasterDB_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) Rollback(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// CustomerRepositoryMock_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type CustomerRepositoryMock_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) Rollback(trx interface{}) *CustomerRepositoryMock_Rollback_Call {
	return &CustomerRepositoryMock_Rollback_Call{Call: _e.mock.On("Rollback", trx)}
}

func (_c *CustomerRepositoryMock_Rollback_Call) Run(run func(trx *gorm.DB)) *CustomerRepositoryMock_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_Rollback_Call) Return(dB *gorm.DB) *CustomerRepositoryMock_Rollback_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *CustomerRepositoryMock_Rollback_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *CustomerRepositoryMock_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// SlaveDB provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) SlaveDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SlaveDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// CustomerRepositoryMock_SlaveDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlaveDB'
type CustomerRepositoryMock_SlaveDB_Call struct {
	*mock.Call
}

// SlaveDB is a helper method to define mock.On call
func (_e *CustomerRepositoryMock_Expecter) SlaveDB() *CustomerRepositoryMock_SlaveDB_Call {
	return &CustomerRepositoryMock_SlaveDB_Call{Call: _e.mock.On("SlaveDB")}
}

func (_c *CustomerRepositoryMock_SlaveDB_Call) Run(run func()) *CustomerRepositoryMock_SlaveDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CustomerRepositoryMock_SlaveDB_Call) Return(dB *gorm.DB) *CustomerRepositoryMock_SlaveDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *CustomerRepositoryMock_SlaveDB_Call) RunAndReturn(run func() *gorm.DB) *CustomerRepositoryMock_SlaveDB_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) Update(ctx context.Context, model customer.Customer, trx *gorm.DB) error {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, customer.Customer, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CustomerRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model customer.Customer
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) Update(ctx interface{}, model interface{}, trx interface{}) *CustomerRepositoryMock_Update_Call {
	return &CustomerRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, model, trx)}
}

func (_c *CustomerRepositoryMock_Update_Call) Run(run func(ctx context.Context, model customer.Customer, trx *gorm.DB)) *CustomerRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 customer.Customer
		if args[1] != nil {
			arg1 = args[1].(customer.Customer)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_Update_Call) Return(err error) *CustomerRepositoryMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, model customer.Customer, trx *gorm.DB) error) *CustomerRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateById provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) UpdateById(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (customer.Customer, error) {
	ret := _mock.Called(ctx, ID, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateById")
	}

	var r0 customer.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) (customer.Customer, error)); ok {
		return returnFunc(ctx, ID, payload, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) customer.Customer); ok {
		r0 = returnFunc(ctx, ID, payload, trx)
	} else {
		r0 = ret.Get(0).(customer.Customer)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, payload, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CustomerRepositoryMock_UpdateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateById'
type CustomerRepositoryMock_UpdateById_Call struct {
	*mock.Call
}

// UpdateById is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) UpdateById(ctx interface{}, ID interface{}, payload interface{}, trx interface{}) *CustomerRepositoryMock_UpdateById_Call {
	return &CustomerRepositoryMock_UpdateById_Call{Call: _e.mock.On("UpdateById", ctx, ID, payload, trx)}
}

func (_c *CustomerRepositoryMock_UpdateById_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB)) *CustomerRepositoryMock_UpdateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_UpdateById_Call) Return(customer1 customer.Customer, err error) *CustomerRepositoryMock_UpdateById_Call {
	_c.Call.Return(customer1, err)
	return _c
}

func (_c *CustomerRepositoryMock_UpdateById_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (customer.Customer, error)) *CustomerRepositoryMock_UpdateById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByIds provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) UpdateByIds(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByIds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerRepositoryMock_UpdateByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByIds'
type CustomerRepositoryMock_UpdateByIds_Call struct {
	*mock.Call
}

// UpdateByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) UpdateByIds(ctx interface{}, IDs interface{}, payload interface{}, trx interface{}) *CustomerRepositoryMock_UpdateByIds_Call {
	return &CustomerRepositoryMock_UpdateByIds_Call{Call: _e.mock.On("UpdateByIds", ctx, IDs, payload, trx)}
}

func (_c *CustomerRepositoryMock_UpdateByIds_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB)) *CustomerRepositoryMock_UpdateByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_UpdateByIds_Call) Return(err error) *CustomerRepositoryMock_UpdateByIds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerRepositoryMock_UpdateByIds_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error) *CustomerRepositoryMock_UpdateByIds_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type CustomerRepositoryMock
func (_mock *CustomerRepositoryMock) UpdateMany(ctx context.Context, filter map[string]any, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, filter, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, filter, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CustomerRepositoryMock_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type CustomerRepositoryMock_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *CustomerRepositoryMock_Expecter) UpdateMany(ctx interface{}, filter interface{}, payload interface{}, trx interface{}) *CustomerRepositoryMock_UpdateMany_Call {
	return &CustomerRepositoryMock_UpdateMany_Call{Call: _e.mock.On("UpdateMany", ctx, filter, payload, trx)}
}

func (_c *CustomerRepositoryMock_UpdateMany_Call) Run(run func(ctx context.Context, filter map[string]any, payload map[string]any, trx *gorm.DB)) *CustomerRepositoryMock_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CustomerRepositoryMock_UpdateMany_Call) Return(err error) *CustomerRepositoryMock_UpdateMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CustomerRepositoryMock_UpdateMany_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, payload map[string]any, trx *gorm.DB) error) *CustomerRepositoryMock_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}
