// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mail

import (
	"context"

	"github.com/goodone-dev/go-boilerplate/internal/domain/mail"
	mock "github.com/stretchr/testify/mock"
)

// NewMailUsecaseMock creates a new instance of MailUsecaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailUsecaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailUsecaseMock {
	mock := &MailUsecaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MailUsecaseMock is an autogenerated mock type for the MailUsecase type
type MailUsecaseMock struct {
	mock.Mock
}

type MailUsecaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MailUsecaseMock) EXPECT() *MailUsecaseMock_Expecter {
	return &MailUsecaseMock_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MailUsecaseMock
func (_mock *MailUsecaseMock) Send(ctx context.Context, req mail.MailSendMessage) error {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, mail.MailSendMessage) error); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MailUsecaseMock_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MailUsecaseMock_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - req mail.MailSendMessage
func (_e *MailUsecaseMock_Expecter) Send(ctx interface{}, req interface{}) *MailUsecaseMock_Send_Call {
	return &MailUsecaseMock_Send_Call{Call: _e.mock.On("Send", ctx, req)}
}

func (_c *MailUsecaseMock_Send_Call) Run(run func(ctx context.Context, req mail.MailSendMessage)) *MailUsecaseMock_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 mail.MailSendMessage
		if args[1] != nil {
			arg1 = args[1].(mail.MailSendMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MailUsecaseMock_Send_Call) Return(err error) *MailUsecaseMock_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MailUsecaseMock_Send_Call) RunAndReturn(run func(ctx context.Context, req mail.MailSendMessage) error) *MailUsecaseMock_Send_Call {
	_c.Call.Return(run)
	return _c
}
