INSERT INTO products (id, name, description, price, stock) VALUES
(gen_random_uuid(), 'Laptop Pro', 'High-performance laptop for professionals', 1200.00, 50),
(gen_random_uuid(), 'Smartphone X', 'Latest model with advanced features', 800.00, 150),
(gen_random_uuid(), 'Wireless Headphones', 'Noise-cancelling over-ear headphones', 250.00, 300),
(gen_random_uuid(), 'Smartwatch 2', 'Fitness tracking and mobile notifications', 180.00, 200),
(gen_random_uuid(), '4K Monitor', '27-inch monitor with ultra-high definition', 450.00, 80),
(gen_random_uuid(), 'Mechanical Keyboard', 'RGB backlit keyboard for gaming', 120.00, 120),
(gen_random_uuid(), 'Webcam HD', '1080p webcam for video conferencing', 60.00, 250),
(gen_random_uuid(), 'USB-C Hub', 'Multi-port adapter for laptops', 40.00, 400),
(gen_random_uuid(), 'External SSD 1TB', 'High-speed portable storage', 150.00, 100),
(gen_random_uuid(), 'Gaming Mouse', 'Ergonomic mouse with customizable buttons', 80.00, 180),
(gen_random_uuid(), 'Standing Desk', 'Adjustable height desk for home office', 350.00, 60),
(gen_random_uuid(), 'Ergonomic Chair', 'Office chair with lumbar support', 280.00, 90),
(gen_random_uuid(), 'LED Desk Lamp', 'Modern lamp with adjustable brightness', 35.00, 300),
(gen_random_uuid(), 'Portable Charger', '20000mAh power bank for mobile devices', 50.00, 220),
(gen_random_uuid(), 'Bluetooth Speaker', 'Waterproof speaker for outdoor use', 70.00, 170),
(gen_random_uuid(), 'Graphics Tablet', 'For digital drawing and photo editing', 100.00, 110),
(gen_random_uuid(), 'VR Headset', 'Immersive virtual reality experience', 400.00, 70),
(gen_random_uuid(), 'Drone with Camera', '4K video recording drone', 600.00, 40),
(gen_random_uuid(), 'E-reader', 'Backlit e-reader with long battery life', 130.00, 190),
(gen_random_uuid(), 'Fitness Tracker', 'Monitors heart rate and daily activity', 60.00, 280),
(gen_random_uuid(), 'Electric Toothbrush', 'With multiple cleaning modes', 90.00, 140),
(gen_random_uuid(), 'Coffee Maker', '12-cup programmable coffee machine', 80.00, 160),
(gen_random_uuid(), 'Blender', 'High-speed blender for smoothies', 110.00, 130),
(gen_random_uuid(), 'Air Fryer', 'For healthy, oil-free cooking', 100.00, 200),
(gen_random_uuid(), 'Robot Vacuum', 'Automated cleaning for your home', 300.00, 80),
(gen_random_uuid(), 'Security Camera', 'Indoor/outdoor security camera', 120.00, 150),
(gen_random_uuid(), 'Smart Thermostat', 'Energy-saving home thermostat', 150.00, 100),
(gen_random_uuid(), 'Wi-Fi Router', 'High-speed dual-band router', 100.00, 180),
(gen_random_uuid(), 'Projector', '1080p home theater projector', 500.00, 50),
(gen_random_uuid(), 'Soundbar', 'For enhanced TV audio', 200.00, 90),
(gen_random_uuid(), 'Action Camera', 'Waterproof camera for sports', 250.00, 120),
(gen_random_uuid(), 'Digital Photo Frame', 'Displays a slideshow of your photos', 70.00, 200),
(gen_random_uuid(), 'Electric Kettle', 'Fast-boiling water kettle', 40.00, 250),
(gen_random_uuid(), 'Microwave Oven', 'Compact microwave for small spaces', 90.00, 110),
(gen_random_uuid(), 'Toaster', '2-slice toaster with wide slots', 30.00, 300),
(gen_random_uuid(), 'Hair Dryer', 'Ionic hair dryer for fast drying', 50.00, 170),
(gen_random_uuid(), 'Electric Shaver', 'For a close and comfortable shave', 80.00, 140),
(gen_random_uuid(), 'Yoga Mat', 'Non-slip mat for yoga and exercise', 25.00, 400),
(gen_random_uuid(), 'Dumbbell Set', 'Adjustable dumbbell set for home gym', 150.00, 80),
(gen_random_uuid(), 'Resistance Bands', 'Set of 5 bands for strength training', 20.00, 500),
(gen_random_uuid(), 'Water Bottle', 'Insulated stainless steel water bottle', 20.00, 600),
(gen_random_uuid(), 'Backpack', 'Durable backpack for travel and work', 60.00, 250),
(gen_random_uuid(), 'Sunglasses', 'UV protection sunglasses', 40.00, 350),
(gen_random_uuid(), 'Wristwatch', 'Classic analog wristwatch', 120.00, 180),
(gen_random_uuid(), 'Wallet', 'Leather wallet with RFID blocking', 30.00, 400),
(gen_random_uuid(), 'Desk Organizer', 'Keeps your desk tidy', 20.00, 300),
(gen_random_uuid(), 'Notebook and Pen Set', 'Premium notebook and pen', 25.00, 450),
(gen_random_uuid(), 'Wall Art', 'Abstract canvas print for home decor', 80.00, 120),
(gen_random_uuid(), 'Scented Candle', 'Soy wax candle with lavender scent', 15.00, 500),
(gen_random_uuid(), 'Board Game', 'Strategy board game for game night', 40.00, 200);