// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rabbitmq

import (
	"context"

	"github.com/goodone-dev/go-boilerplate/internal/infrastructure/messaging/rabbitmq"
	"github.com/rabbitmq/amqp091-go"
	mock "github.com/stretchr/testify/mock"
)

// NewClientMock creates a new instance of ClientMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientMock is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

type ClientMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientMock) EXPECT() *ClientMock_Expecter {
	return &ClientMock_Expecter{mock: &_m.Mock}
}

// BindQueue provides a mock function for the type ClientMock
func (_mock *ClientMock) BindQueue(queueName string, routingKey string, exchangeName string, args amqp091.Table) error {
	ret := _mock.Called(queueName, routingKey, exchangeName, args)

	if len(ret) == 0 {
		panic("no return value specified for BindQueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, amqp091.Table) error); ok {
		r0 = returnFunc(queueName, routingKey, exchangeName, args)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_BindQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindQueue'
type ClientMock_BindQueue_Call struct {
	*mock.Call
}

// BindQueue is a helper method to define mock.On call
//   - queueName string
//   - routingKey string
//   - exchangeName string
//   - args amqp091.Table
func (_e *ClientMock_Expecter) BindQueue(queueName interface{}, routingKey interface{}, exchangeName interface{}, args interface{}) *ClientMock_BindQueue_Call {
	return &ClientMock_BindQueue_Call{Call: _e.mock.On("BindQueue", queueName, routingKey, exchangeName, args)}
}

func (_c *ClientMock_BindQueue_Call) Run(run func(queueName string, routingKey string, exchangeName string, args amqp091.Table)) *ClientMock_BindQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 amqp091.Table
		if args[3] != nil {
			arg3 = args[3].(amqp091.Table)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ClientMock_BindQueue_Call) Return(err error) *ClientMock_BindQueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_BindQueue_Call) RunAndReturn(run func(queueName string, routingKey string, exchangeName string, args amqp091.Table) error) *ClientMock_BindQueue_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function for the type ClientMock
func (_mock *ClientMock) Consume(ctx context.Context, config rabbitmq.ConsumeConfig, handler rabbitmq.DeliveryHandler) error {
	ret := _mock.Called(ctx, config, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rabbitmq.ConsumeConfig, rabbitmq.DeliveryHandler) error); ok {
		r0 = returnFunc(ctx, config, handler)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type ClientMock_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - config rabbitmq.ConsumeConfig
//   - handler rabbitmq.DeliveryHandler
func (_e *ClientMock_Expecter) Consume(ctx interface{}, config interface{}, handler interface{}) *ClientMock_Consume_Call {
	return &ClientMock_Consume_Call{Call: _e.mock.On("Consume", ctx, config, handler)}
}

func (_c *ClientMock_Consume_Call) Run(run func(ctx context.Context, config rabbitmq.ConsumeConfig, handler rabbitmq.DeliveryHandler)) *ClientMock_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rabbitmq.ConsumeConfig
		if args[1] != nil {
			arg1 = args[1].(rabbitmq.ConsumeConfig)
		}
		var arg2 rabbitmq.DeliveryHandler
		if args[2] != nil {
			arg2 = args[2].(rabbitmq.DeliveryHandler)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientMock_Consume_Call) Return(err error) *ClientMock_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Consume_Call) RunAndReturn(run func(ctx context.Context, config rabbitmq.ConsumeConfig, handler rabbitmq.DeliveryHandler) error) *ClientMock_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// DeclareExchange provides a mock function for the type ClientMock
func (_mock *ClientMock) DeclareExchange(config rabbitmq.ExchangeConfig) error {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for DeclareExchange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(rabbitmq.ExchangeConfig) error); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_DeclareExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclareExchange'
type ClientMock_DeclareExchange_Call struct {
	*mock.Call
}

// DeclareExchange is a helper method to define mock.On call
//   - config rabbitmq.ExchangeConfig
func (_e *ClientMock_Expecter) DeclareExchange(config interface{}) *ClientMock_DeclareExchange_Call {
	return &ClientMock_DeclareExchange_Call{Call: _e.mock.On("DeclareExchange", config)}
}

func (_c *ClientMock_DeclareExchange_Call) Run(run func(config rabbitmq.ExchangeConfig)) *ClientMock_DeclareExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rabbitmq.ExchangeConfig
		if args[0] != nil {
			arg0 = args[0].(rabbitmq.ExchangeConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientMock_DeclareExchange_Call) Return(err error) *ClientMock_DeclareExchange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_DeclareExchange_Call) RunAndReturn(run func(config rabbitmq.ExchangeConfig) error) *ClientMock_DeclareExchange_Call {
	_c.Call.Return(run)
	return _c
}

// DeclareQueue provides a mock function for the type ClientMock
func (_mock *ClientMock) DeclareQueue(config rabbitmq.QueueConfig) (amqp091.Queue, error) {
	ret := _mock.Called(config)

	if len(ret) == 0 {
		panic("no return value specified for DeclareQueue")
	}

	var r0 amqp091.Queue
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(rabbitmq.QueueConfig) (amqp091.Queue, error)); ok {
		return returnFunc(config)
	}
	if returnFunc, ok := ret.Get(0).(func(rabbitmq.QueueConfig) amqp091.Queue); ok {
		r0 = returnFunc(config)
	} else {
		r0 = ret.Get(0).(amqp091.Queue)
	}
	if returnFunc, ok := ret.Get(1).(func(rabbitmq.QueueConfig) error); ok {
		r1 = returnFunc(config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_DeclareQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeclareQueue'
type ClientMock_DeclareQueue_Call struct {
	*mock.Call
}

// DeclareQueue is a helper method to define mock.On call
//   - config rabbitmq.QueueConfig
func (_e *ClientMock_Expecter) DeclareQueue(config interface{}) *ClientMock_DeclareQueue_Call {
	return &ClientMock_DeclareQueue_Call{Call: _e.mock.On("DeclareQueue", config)}
}

func (_c *ClientMock_DeclareQueue_Call) Run(run func(config rabbitmq.QueueConfig)) *ClientMock_DeclareQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 rabbitmq.QueueConfig
		if args[0] != nil {
			arg0 = args[0].(rabbitmq.QueueConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientMock_DeclareQueue_Call) Return(queue amqp091.Queue, err error) *ClientMock_DeclareQueue_Call {
	_c.Call.Return(queue, err)
	return _c
}

func (_c *ClientMock_DeclareQueue_Call) RunAndReturn(run func(config rabbitmq.QueueConfig) (amqp091.Queue, error)) *ClientMock_DeclareQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannel provides a mock function for the type ClientMock
func (_mock *ClientMock) GetChannel() (*amqp091.Channel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 *amqp091.Channel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*amqp091.Channel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *amqp091.Channel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*amqp091.Channel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientMock_GetChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannel'
type ClientMock_GetChannel_Call struct {
	*mock.Call
}

// GetChannel is a helper method to define mock.On call
func (_e *ClientMock_Expecter) GetChannel() *ClientMock_GetChannel_Call {
	return &ClientMock_GetChannel_Call{Call: _e.mock.On("GetChannel")}
}

func (_c *ClientMock_GetChannel_Call) Run(run func()) *ClientMock_GetChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClientMock_GetChannel_Call) Return(channel *amqp091.Channel, err error) *ClientMock_GetChannel_Call {
	_c.Call.Return(channel, err)
	return _c
}

func (_c *ClientMock_GetChannel_Call) RunAndReturn(run func() (*amqp091.Channel, error)) *ClientMock_GetChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type ClientMock
func (_mock *ClientMock) Publish(ctx context.Context, config rabbitmq.PublishConfig, msg rabbitmq.Message) error {
	ret := _mock.Called(ctx, config, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, rabbitmq.PublishConfig, rabbitmq.Message) error); ok {
		r0 = returnFunc(ctx, config, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type ClientMock_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - config rabbitmq.PublishConfig
//   - msg rabbitmq.Message
func (_e *ClientMock_Expecter) Publish(ctx interface{}, config interface{}, msg interface{}) *ClientMock_Publish_Call {
	return &ClientMock_Publish_Call{Call: _e.mock.On("Publish", ctx, config, msg)}
}

func (_c *ClientMock_Publish_Call) Run(run func(ctx context.Context, config rabbitmq.PublishConfig, msg rabbitmq.Message)) *ClientMock_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 rabbitmq.PublishConfig
		if args[1] != nil {
			arg1 = args[1].(rabbitmq.PublishConfig)
		}
		var arg2 rabbitmq.Message
		if args[2] != nil {
			arg2 = args[2].(rabbitmq.Message)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ClientMock_Publish_Call) Return(err error) *ClientMock_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Publish_Call) RunAndReturn(run func(ctx context.Context, config rabbitmq.PublishConfig, msg rabbitmq.Message) error) *ClientMock_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type ClientMock
func (_mock *ClientMock) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientMock_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ClientMock_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ClientMock_Expecter) Shutdown(ctx interface{}) *ClientMock_Shutdown_Call {
	return &ClientMock_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *ClientMock_Shutdown_Call) Run(run func(ctx context.Context)) *ClientMock_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientMock_Shutdown_Call) Return(err error) *ClientMock_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientMock_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *ClientMock_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
