// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package employee

import (
	"context"

	"github.com/goodone-dev/go-boilerplate/internal/domain/employee"
	"github.com/goodone-dev/go-boilerplate/internal/infrastructure/database"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"gorm.io/gorm"
)

// NewEmployeeRepositoryMock creates a new instance of EmployeeRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmployeeRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmployeeRepositoryMock {
	mock := &EmployeeRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmployeeRepositoryMock is an autogenerated mock type for the EmployeeRepository type
type EmployeeRepositoryMock struct {
	mock.Mock
}

type EmployeeRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EmployeeRepositoryMock) EXPECT() *EmployeeRepositoryMock_Expecter {
	return &EmployeeRepositoryMock_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) Begin(ctx context.Context) (*gorm.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 *gorm.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type EmployeeRepositoryMock_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EmployeeRepositoryMock_Expecter) Begin(ctx interface{}) *EmployeeRepositoryMock_Begin_Call {
	return &EmployeeRepositoryMock_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *EmployeeRepositoryMock_Begin_Call) Run(run func(ctx context.Context)) *EmployeeRepositoryMock_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_Begin_Call) Return(dB *gorm.DB, err error) *EmployeeRepositoryMock_Begin_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *EmployeeRepositoryMock_Begin_Call) RunAndReturn(run func(ctx context.Context) (*gorm.DB, error)) *EmployeeRepositoryMock_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) Commit(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// EmployeeRepositoryMock_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type EmployeeRepositoryMock_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) Commit(trx interface{}) *EmployeeRepositoryMock_Commit_Call {
	return &EmployeeRepositoryMock_Commit_Call{Call: _e.mock.On("Commit", trx)}
}

func (_c *EmployeeRepositoryMock_Commit_Call) Run(run func(trx *gorm.DB)) *EmployeeRepositoryMock_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_Commit_Call) Return(dB *gorm.DB) *EmployeeRepositoryMock_Commit_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *EmployeeRepositoryMock_Commit_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *EmployeeRepositoryMock_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteById provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) DeleteById(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepositoryMock_DeleteById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteById'
type EmployeeRepositoryMock_DeleteById_Call struct {
	*mock.Call
}

// DeleteById is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) DeleteById(ctx interface{}, ID interface{}, trx interface{}) *EmployeeRepositoryMock_DeleteById_Call {
	return &EmployeeRepositoryMock_DeleteById_Call{Call: _e.mock.On("DeleteById", ctx, ID, trx)}
}

func (_c *EmployeeRepositoryMock_DeleteById_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *EmployeeRepositoryMock_DeleteById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_DeleteById_Call) Return(err error) *EmployeeRepositoryMock_DeleteById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepositoryMock_DeleteById_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) error) *EmployeeRepositoryMock_DeleteById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByIds provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) DeleteByIds(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByIds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepositoryMock_DeleteByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByIds'
type EmployeeRepositoryMock_DeleteByIds_Call struct {
	*mock.Call
}

// DeleteByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) DeleteByIds(ctx interface{}, IDs interface{}, trx interface{}) *EmployeeRepositoryMock_DeleteByIds_Call {
	return &EmployeeRepositoryMock_DeleteByIds_Call{Call: _e.mock.On("DeleteByIds", ctx, IDs, trx)}
}

func (_c *EmployeeRepositoryMock_DeleteByIds_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB)) *EmployeeRepositoryMock_DeleteByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_DeleteByIds_Call) Return(err error) *EmployeeRepositoryMock_DeleteByIds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepositoryMock_DeleteByIds_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, trx *gorm.DB) error) *EmployeeRepositoryMock_DeleteByIds_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) DeleteMany(ctx context.Context, filter map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, filter, trx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, filter, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepositoryMock_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type EmployeeRepositoryMock_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) DeleteMany(ctx interface{}, filter interface{}, trx interface{}) *EmployeeRepositoryMock_DeleteMany_Call {
	return &EmployeeRepositoryMock_DeleteMany_Call{Call: _e.mock.On("DeleteMany", ctx, filter, trx)}
}

func (_c *EmployeeRepositoryMock_DeleteMany_Call) Run(run func(ctx context.Context, filter map[string]any, trx *gorm.DB)) *EmployeeRepositoryMock_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_DeleteMany_Call) Return(err error) *EmployeeRepositoryMock_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepositoryMock_DeleteMany_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, trx *gorm.DB) error) *EmployeeRepositoryMock_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) FindAll(ctx context.Context, filter map[string]any) ([]employee.Employee, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) ([]employee.Employee, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any) []employee.Employee); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type EmployeeRepositoryMock_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
func (_e *EmployeeRepositoryMock_Expecter) FindAll(ctx interface{}, filter interface{}) *EmployeeRepositoryMock_FindAll_Call {
	return &EmployeeRepositoryMock_FindAll_Call{Call: _e.mock.On("FindAll", ctx, filter)}
}

func (_c *EmployeeRepositoryMock_FindAll_Call) Run(run func(ctx context.Context, filter map[string]any)) *EmployeeRepositoryMock_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_FindAll_Call) Return(employees []employee.Employee, err error) *EmployeeRepositoryMock_FindAll_Call {
	_c.Call.Return(employees, err)
	return _c
}

func (_c *EmployeeRepositoryMock_FindAll_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any) ([]employee.Employee, error)) *EmployeeRepositoryMock_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCursor provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) FindByCursor(ctx context.Context, filter map[string]any, sort []string, size int, next *uuid.UUID) (database.Pagination[employee.Employee], error) {
	ret := _mock.Called(ctx, filter, sort, size, next)

	if len(ret) == 0 {
		panic("no return value specified for FindByCursor")
	}

	var r0 database.Pagination[employee.Employee]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, *uuid.UUID) (database.Pagination[employee.Employee], error)); ok {
		return returnFunc(ctx, filter, sort, size, next)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, *uuid.UUID) database.Pagination[employee.Employee]); ok {
		r0 = returnFunc(ctx, filter, sort, size, next)
	} else {
		r0 = ret.Get(0).(database.Pagination[employee.Employee])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, []string, int, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, filter, sort, size, next)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_FindByCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCursor'
type EmployeeRepositoryMock_FindByCursor_Call struct {
	*mock.Call
}

// FindByCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - sort []string
//   - size int
//   - next *uuid.UUID
func (_e *EmployeeRepositoryMock_Expecter) FindByCursor(ctx interface{}, filter interface{}, sort interface{}, size interface{}, next interface{}) *EmployeeRepositoryMock_FindByCursor_Call {
	return &EmployeeRepositoryMock_FindByCursor_Call{Call: _e.mock.On("FindByCursor", ctx, filter, sort, size, next)}
}

func (_c *EmployeeRepositoryMock_FindByCursor_Call) Run(run func(ctx context.Context, filter map[string]any, sort []string, size int, next *uuid.UUID)) *EmployeeRepositoryMock_FindByCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 *uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(*uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_FindByCursor_Call) Return(res database.Pagination[employee.Employee], err error) *EmployeeRepositoryMock_FindByCursor_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *EmployeeRepositoryMock_FindByCursor_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, sort []string, size int, next *uuid.UUID) (database.Pagination[employee.Employee], error)) *EmployeeRepositoryMock_FindByCursor_Call {
	_c.Call.Return(run)
	return _c
}

// FindById provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) FindById(ctx context.Context, ID uuid.UUID) (*employee.Employee, error) {
	ret := _mock.Called(ctx, ID)

	if len(ret) == 0 {
		panic("no return value specified for FindById")
	}

	var r0 *employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*employee.Employee, error)); ok {
		return returnFunc(ctx, ID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *employee.Employee); ok {
		r0 = returnFunc(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_FindById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindById'
type EmployeeRepositoryMock_FindById_Call struct {
	*mock.Call
}

// FindById is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
func (_e *EmployeeRepositoryMock_Expecter) FindById(ctx interface{}, ID interface{}) *EmployeeRepositoryMock_FindById_Call {
	return &EmployeeRepositoryMock_FindById_Call{Call: _e.mock.On("FindById", ctx, ID)}
}

func (_c *EmployeeRepositoryMock_FindById_Call) Run(run func(ctx context.Context, ID uuid.UUID)) *EmployeeRepositoryMock_FindById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_FindById_Call) Return(employee1 *employee.Employee, err error) *EmployeeRepositoryMock_FindById_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *EmployeeRepositoryMock_FindById_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID) (*employee.Employee, error)) *EmployeeRepositoryMock_FindById_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIdAndLock provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) FindByIdAndLock(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (*employee.Employee, error) {
	ret := _mock.Called(ctx, ID, trx)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdAndLock")
	}

	var r0 *employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) (*employee.Employee, error)); ok {
		return returnFunc(ctx, ID, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *gorm.DB) *employee.Employee); ok {
		r0 = returnFunc(ctx, ID, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_FindByIdAndLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIdAndLock'
type EmployeeRepositoryMock_FindByIdAndLock_Call struct {
	*mock.Call
}

// FindByIdAndLock is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) FindByIdAndLock(ctx interface{}, ID interface{}, trx interface{}) *EmployeeRepositoryMock_FindByIdAndLock_Call {
	return &EmployeeRepositoryMock_FindByIdAndLock_Call{Call: _e.mock.On("FindByIdAndLock", ctx, ID, trx)}
}

func (_c *EmployeeRepositoryMock_FindByIdAndLock_Call) Run(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB)) *EmployeeRepositoryMock_FindByIdAndLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_FindByIdAndLock_Call) Return(employee1 *employee.Employee, err error) *EmployeeRepositoryMock_FindByIdAndLock_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *EmployeeRepositoryMock_FindByIdAndLock_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, trx *gorm.DB) (*employee.Employee, error)) *EmployeeRepositoryMock_FindByIdAndLock_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIds provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) FindByIds(ctx context.Context, IDs []uuid.UUID) ([]employee.Employee, error) {
	ret := _mock.Called(ctx, IDs)

	if len(ret) == 0 {
		panic("no return value specified for FindByIds")
	}

	var r0 []employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]employee.Employee, error)); ok {
		return returnFunc(ctx, IDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []employee.Employee); ok {
		r0 = returnFunc(ctx, IDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, IDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_FindByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIds'
type EmployeeRepositoryMock_FindByIds_Call struct {
	*mock.Call
}

// FindByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
func (_e *EmployeeRepositoryMock_Expecter) FindByIds(ctx interface{}, IDs interface{}) *EmployeeRepositoryMock_FindByIds_Call {
	return &EmployeeRepositoryMock_FindByIds_Call{Call: _e.mock.On("FindByIds", ctx, IDs)}
}

func (_c *EmployeeRepositoryMock_FindByIds_Call) Run(run func(ctx context.Context, IDs []uuid.UUID)) *EmployeeRepositoryMock_FindByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_FindByIds_Call) Return(employees []employee.Employee, err error) *EmployeeRepositoryMock_FindByIds_Call {
	_c.Call.Return(employees, err)
	return _c
}

func (_c *EmployeeRepositoryMock_FindByIds_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID) ([]employee.Employee, error)) *EmployeeRepositoryMock_FindByIds_Call {
	_c.Call.Return(run)
	return _c
}

// FindByOffset provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) FindByOffset(ctx context.Context, filter map[string]any, sort []string, size int, page int) (database.Pagination[employee.Employee], error) {
	ret := _mock.Called(ctx, filter, sort, size, page)

	if len(ret) == 0 {
		panic("no return value specified for FindByOffset")
	}

	var r0 database.Pagination[employee.Employee]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, int) (database.Pagination[employee.Employee], error)); ok {
		return returnFunc(ctx, filter, sort, size, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, []string, int, int) database.Pagination[employee.Employee]); ok {
		r0 = returnFunc(ctx, filter, sort, size, page)
	} else {
		r0 = ret.Get(0).(database.Pagination[employee.Employee])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, map[string]any, []string, int, int) error); ok {
		r1 = returnFunc(ctx, filter, sort, size, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_FindByOffset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByOffset'
type EmployeeRepositoryMock_FindByOffset_Call struct {
	*mock.Call
}

// FindByOffset is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - sort []string
//   - size int
//   - page int
func (_e *EmployeeRepositoryMock_Expecter) FindByOffset(ctx interface{}, filter interface{}, sort interface{}, size interface{}, page interface{}) *EmployeeRepositoryMock_FindByOffset_Call {
	return &EmployeeRepositoryMock_FindByOffset_Call{Call: _e.mock.On("FindByOffset", ctx, filter, sort, size, page)}
}

func (_c *EmployeeRepositoryMock_FindByOffset_Call) Run(run func(ctx context.Context, filter map[string]any, sort []string, size int, page int)) *EmployeeRepositoryMock_FindByOffset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_FindByOffset_Call) Return(res database.Pagination[employee.Employee], err error) *EmployeeRepositoryMock_FindByOffset_Call {
	_c.Call.Return(res, err)
	return _c
}

func (_c *EmployeeRepositoryMock_FindByOffset_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, sort []string, size int, page int) (database.Pagination[employee.Employee], error)) *EmployeeRepositoryMock_FindByOffset_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) Insert(ctx context.Context, model employee.Employee, trx *gorm.DB) (employee.Employee, error) {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee, *gorm.DB) (employee.Employee, error)); ok {
		return returnFunc(ctx, model, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee, *gorm.DB) employee.Employee); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, employee.Employee, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, model, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type EmployeeRepositoryMock_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - model employee.Employee
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) Insert(ctx interface{}, model interface{}, trx interface{}) *EmployeeRepositoryMock_Insert_Call {
	return &EmployeeRepositoryMock_Insert_Call{Call: _e.mock.On("Insert", ctx, model, trx)}
}

func (_c *EmployeeRepositoryMock_Insert_Call) Run(run func(ctx context.Context, model employee.Employee, trx *gorm.DB)) *EmployeeRepositoryMock_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 employee.Employee
		if args[1] != nil {
			arg1 = args[1].(employee.Employee)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_Insert_Call) Return(employee1 employee.Employee, err error) *EmployeeRepositoryMock_Insert_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *EmployeeRepositoryMock_Insert_Call) RunAndReturn(run func(ctx context.Context, model employee.Employee, trx *gorm.DB) (employee.Employee, error)) *EmployeeRepositoryMock_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) InsertMany(ctx context.Context, models []employee.Employee, trx *gorm.DB) ([]employee.Employee, error) {
	ret := _mock.Called(ctx, models, trx)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 []employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []employee.Employee, *gorm.DB) ([]employee.Employee, error)); ok {
		return returnFunc(ctx, models, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []employee.Employee, *gorm.DB) []employee.Employee); ok {
		r0 = returnFunc(ctx, models, trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]employee.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []employee.Employee, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, models, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type EmployeeRepositoryMock_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - ctx context.Context
//   - models []employee.Employee
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) InsertMany(ctx interface{}, models interface{}, trx interface{}) *EmployeeRepositoryMock_InsertMany_Call {
	return &EmployeeRepositoryMock_InsertMany_Call{Call: _e.mock.On("InsertMany", ctx, models, trx)}
}

func (_c *EmployeeRepositoryMock_InsertMany_Call) Run(run func(ctx context.Context, models []employee.Employee, trx *gorm.DB)) *EmployeeRepositoryMock_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []employee.Employee
		if args[1] != nil {
			arg1 = args[1].([]employee.Employee)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_InsertMany_Call) Return(employees []employee.Employee, err error) *EmployeeRepositoryMock_InsertMany_Call {
	_c.Call.Return(employees, err)
	return _c
}

func (_c *EmployeeRepositoryMock_InsertMany_Call) RunAndReturn(run func(ctx context.Context, models []employee.Employee, trx *gorm.DB) ([]employee.Employee, error)) *EmployeeRepositoryMock_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// MasterDB provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) MasterDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MasterDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// EmployeeRepositoryMock_MasterDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MasterDB'
type EmployeeRepositoryMock_MasterDB_Call struct {
	*mock.Call
}

// MasterDB is a helper method to define mock.On call
func (_e *EmployeeRepositoryMock_Expecter) MasterDB() *EmployeeRepositoryMock_MasterDB_Call {
	return &EmployeeRepositoryMock_MasterDB_Call{Call: _e.mock.On("MasterDB")}
}

func (_c *EmployeeRepositoryMock_MasterDB_Call) Run(run func()) *EmployeeRepositoryMock_MasterDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EmployeeRepositoryMock_MasterDB_Call) Return(dB *gorm.DB) *EmployeeRepositoryMock_MasterDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *EmployeeRepositoryMock_MasterDB_Call) RunAndReturn(run func() *gorm.DB) *EmployeeRepositoryMock_MasterDB_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) Rollback(trx *gorm.DB) *gorm.DB {
	ret := _mock.Called(trx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func(*gorm.DB) *gorm.DB); ok {
		r0 = returnFunc(trx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// EmployeeRepositoryMock_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type EmployeeRepositoryMock_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) Rollback(trx interface{}) *EmployeeRepositoryMock_Rollback_Call {
	return &EmployeeRepositoryMock_Rollback_Call{Call: _e.mock.On("Rollback", trx)}
}

func (_c *EmployeeRepositoryMock_Rollback_Call) Run(run func(trx *gorm.DB)) *EmployeeRepositoryMock_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_Rollback_Call) Return(dB *gorm.DB) *EmployeeRepositoryMock_Rollback_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *EmployeeRepositoryMock_Rollback_Call) RunAndReturn(run func(trx *gorm.DB) *gorm.DB) *EmployeeRepositoryMock_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// SlaveDB provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) SlaveDB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SlaveDB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// EmployeeRepositoryMock_SlaveDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlaveDB'
type EmployeeRepositoryMock_SlaveDB_Call struct {
	*mock.Call
}

// SlaveDB is a helper method to define mock.On call
func (_e *EmployeeRepositoryMock_Expecter) SlaveDB() *EmployeeRepositoryMock_SlaveDB_Call {
	return &EmployeeRepositoryMock_SlaveDB_Call{Call: _e.mock.On("SlaveDB")}
}

func (_c *EmployeeRepositoryMock_SlaveDB_Call) Run(run func()) *EmployeeRepositoryMock_SlaveDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EmployeeRepositoryMock_SlaveDB_Call) Return(dB *gorm.DB) *EmployeeRepositoryMock_SlaveDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *EmployeeRepositoryMock_SlaveDB_Call) RunAndReturn(run func() *gorm.DB) *EmployeeRepositoryMock_SlaveDB_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) Update(ctx context.Context, model employee.Employee, trx *gorm.DB) error {
	ret := _mock.Called(ctx, model, trx)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, employee.Employee, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, model, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type EmployeeRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - model employee.Employee
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) Update(ctx interface{}, model interface{}, trx interface{}) *EmployeeRepositoryMock_Update_Call {
	return &EmployeeRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, model, trx)}
}

func (_c *EmployeeRepositoryMock_Update_Call) Run(run func(ctx context.Context, model employee.Employee, trx *gorm.DB)) *EmployeeRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 employee.Employee
		if args[1] != nil {
			arg1 = args[1].(employee.Employee)
		}
		var arg2 *gorm.DB
		if args[2] != nil {
			arg2 = args[2].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_Update_Call) Return(err error) *EmployeeRepositoryMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, model employee.Employee, trx *gorm.DB) error) *EmployeeRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateById provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) UpdateById(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (employee.Employee, error) {
	ret := _mock.Called(ctx, ID, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateById")
	}

	var r0 employee.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) (employee.Employee, error)); ok {
		return returnFunc(ctx, ID, payload, trx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) employee.Employee); ok {
		r0 = returnFunc(ctx, ID, payload, trx)
	} else {
		r0 = ret.Get(0).(employee.Employee)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r1 = returnFunc(ctx, ID, payload, trx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmployeeRepositoryMock_UpdateById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateById'
type EmployeeRepositoryMock_UpdateById_Call struct {
	*mock.Call
}

// UpdateById is a helper method to define mock.On call
//   - ctx context.Context
//   - ID uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) UpdateById(ctx interface{}, ID interface{}, payload interface{}, trx interface{}) *EmployeeRepositoryMock_UpdateById_Call {
	return &EmployeeRepositoryMock_UpdateById_Call{Call: _e.mock.On("UpdateById", ctx, ID, payload, trx)}
}

func (_c *EmployeeRepositoryMock_UpdateById_Call) Run(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB)) *EmployeeRepositoryMock_UpdateById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_UpdateById_Call) Return(employee1 employee.Employee, err error) *EmployeeRepositoryMock_UpdateById_Call {
	_c.Call.Return(employee1, err)
	return _c
}

func (_c *EmployeeRepositoryMock_UpdateById_Call) RunAndReturn(run func(ctx context.Context, ID uuid.UUID, payload map[string]any, trx *gorm.DB) (employee.Employee, error)) *EmployeeRepositoryMock_UpdateById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByIds provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) UpdateByIds(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, IDs, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByIds")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, IDs, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepositoryMock_UpdateByIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByIds'
type EmployeeRepositoryMock_UpdateByIds_Call struct {
	*mock.Call
}

// UpdateByIds is a helper method to define mock.On call
//   - ctx context.Context
//   - IDs []uuid.UUID
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) UpdateByIds(ctx interface{}, IDs interface{}, payload interface{}, trx interface{}) *EmployeeRepositoryMock_UpdateByIds_Call {
	return &EmployeeRepositoryMock_UpdateByIds_Call{Call: _e.mock.On("UpdateByIds", ctx, IDs, payload, trx)}
}

func (_c *EmployeeRepositoryMock_UpdateByIds_Call) Run(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB)) *EmployeeRepositoryMock_UpdateByIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_UpdateByIds_Call) Return(err error) *EmployeeRepositoryMock_UpdateByIds_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepositoryMock_UpdateByIds_Call) RunAndReturn(run func(ctx context.Context, IDs []uuid.UUID, payload map[string]any, trx *gorm.DB) error) *EmployeeRepositoryMock_UpdateByIds_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMany provides a mock function for the type EmployeeRepositoryMock
func (_mock *EmployeeRepositoryMock) UpdateMany(ctx context.Context, filter map[string]any, payload map[string]any, trx *gorm.DB) error {
	ret := _mock.Called(ctx, filter, payload, trx)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]any, map[string]any, *gorm.DB) error); ok {
		r0 = returnFunc(ctx, filter, payload, trx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmployeeRepositoryMock_UpdateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMany'
type EmployeeRepositoryMock_UpdateMany_Call struct {
	*mock.Call
}

// UpdateMany is a helper method to define mock.On call
//   - ctx context.Context
//   - filter map[string]any
//   - payload map[string]any
//   - trx *gorm.DB
func (_e *EmployeeRepositoryMock_Expecter) UpdateMany(ctx interface{}, filter interface{}, payload interface{}, trx interface{}) *EmployeeRepositoryMock_UpdateMany_Call {
	return &EmployeeRepositoryMock_UpdateMany_Call{Call: _e.mock.On("UpdateMany", ctx, filter, payload, trx)}
}

func (_c *EmployeeRepositoryMock_UpdateMany_Call) Run(run func(ctx context.Context, filter map[string]any, payload map[string]any, trx *gorm.DB)) *EmployeeRepositoryMock_UpdateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]any
		if args[1] != nil {
			arg1 = args[1].(map[string]any)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		var arg3 *gorm.DB
		if args[3] != nil {
			arg3 = args[3].(*gorm.DB)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmployeeRepositoryMock_UpdateMany_Call) Return(err error) *EmployeeRepositoryMock_UpdateMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmployeeRepositoryMock_UpdateMany_Call) RunAndReturn(run func(ctx context.Context, filter map[string]any, payload map[string]any, trx *gorm.DB) error) *EmployeeRepositoryMock_UpdateMany_Call {
	_c.Call.Return(run)
	return _c
}
