// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package health

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHealthServiceMock creates a new instance of HealthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthServiceMock {
	mock := &HealthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HealthServiceMock is an autogenerated mock type for the HealthService type
type HealthServiceMock struct {
	mock.Mock
}

type HealthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HealthServiceMock) EXPECT() *HealthServiceMock_Expecter {
	return &HealthServiceMock_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type HealthServiceMock
func (_mock *HealthServiceMock) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HealthServiceMock_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type HealthServiceMock_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HealthServiceMock_Expecter) Ping(ctx interface{}) *HealthServiceMock_Ping_Call {
	return &HealthServiceMock_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *HealthServiceMock_Ping_Call) Run(run func(ctx context.Context)) *HealthServiceMock_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *HealthServiceMock_Ping_Call) Return(err error) *HealthServiceMock_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HealthServiceMock_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *HealthServiceMock_Ping_Call {
	_c.Call.Return(run)
	return _c
}
