name: Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24.2'

jobs:
  build_check:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Build
        run: go build -v ./...

  lint_check:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: '0' # Number of commits to fetch. 0 indicates all history for all branches and tags.

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          only-new-issues: true # Show only new issues.

  security_check:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: '0' # Number of commits to fetch. 0 indicates all history for all branches and tags.

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Run gosec
        uses: securego/gosec@master
        with:
          args: '-exclude=G115 -r ./...'

  dependency_check:
    name: Dependency Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Dependency Vulnerability Scanning
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '${{ env.GO_VERSION }}'
          go-package: ./...

# TODO: check unit test coverage
